---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-service-admin
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - serviceaccounts
      - services
      - pods
      - pods/log
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - create
      - bind
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelines
      - tasks
    verbs:
      - "*"
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - "get"
      - "create"
      - "update"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "create"
      - "update"
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    verbs:
      - "get"
      - "create"
      - "update"
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot
    resources:
      - securitycontextconstraints
    verbs:
      - use
# this is the start of permissions we have to add so that the pipeline-service-manager can create clusterroles for minio with these permissions.
# we only need this while we are using helm to install minio to work around the stale operator catalogs on hypershift.
  - apiGroups:
      - ""
    resources:
      - pods
      - pod # prior helm runs complained about pod even though I had pods listed here
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - "get"
      - "watch"
      - "list"
      - "patch"
      - "create"
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - "get"
      - "watch"
      - "list"
      - "patch"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - "get"
      - "update"
      - "list"
      - "deletecollection"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - "get"
      - "create"
      - "list"
      - "delete"
      - "watch"
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
      - volumesnapshots
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
      - volumeattachments
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - "create"
      - "patch"
      - "watch"
  - apiGroups:
      - apps
    resources:
      - deployments/finalizers
      - statefulsets
    verbs:
      - "get"
      - "create"
      - "patch"
      - "watch"
      - "delete"
      - "update"
      - "list"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "delete"
      - "patch"
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
    verbs:
      - "get"
      - "create"
      - "delete"
      - "update"
      - "list"
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - beta.eks.amazonaws.com/app-serving
      - kubernetes.io/kube-apiserver-client
      - kubernetes.io/kubelet-serving
      - kubernetes.io/legacy-unknown
    verbs:
      - "approve"
      - "sign"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "get"
      - "create"
      - "update"
      - "list"
      - "watch"
      - "delete"
  - apiGroups:
      - min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - minio.min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - direct.csi.min.io
    resources:
      - directcsidrives
      - directcsivolumes
      - volumes
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "delete"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
    verbs:
      - "*"
# this is the end of permissions we have to add so that the pipeline-service-manager can create clusterroles for minio with these permissions.
  - apiGroups:
      - pipelinesascode.tekton.dev
    resources:
      - repositories
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
